### ISSUE TITLE
Tweet button broken on Field House blog

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#22]
When you try to tweet a story using the Tweet button, it tells you "account suspended." Issue appears to be isolated to the Field House blog, and does not affect other sports blogs. The assumption I'm working off of is that maybe we at one time had a college sports twitter account associated with this blog, and now we don't have it anymore... just a guess though. @freejoe76 @schneidan @danielpetty

**Comment by freejoe76** [comment]
Here's a link to the homepage: http://blogs.denverpost.com/colleges/ . The tweet button with the most-recent post on the homepage worked fine, @danielboniface .

I clicked through to http://blogs.denverpost.com/colleges/2015/11/13/colorado-states-hayden-hunt-punt-guy-semifinalist-for-ray-guy-award/34560/ and clicked the tweet button there, it worked too.

Can you share a URL where the tweet button's broken?

**Comment by schneidan** [comment]
@danielboniface Are you running an ad blocker, or the Disconnect plugin? Disconnect can break Tweet buttons, I know.

**Comment by danielboniface** [comment]
@freejoe76 @schneidan Here's the link where I was getting "account suspended" on the Tweet button: http://blogs.denverpost.com/colleges/2015/10/31/watch-miami-downs-duke-on-eight-lateral-touchdown-play/34401/

**Comment by freejoe76** [comment]
@danielboniface Jeff Bailey's profile on the blog is out of date -- it still has his twitter handle as beetlecr, which is a suspended account. Fix that and the problem will be solved.
