### ISSUE TITLE
Build the framework for the women's 2016 NCAA basketball tournament bracket

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#25]
Same as men's but for the women's tourney. It will be announced at 5 pm. @freejoe76

**Comment by freejoe76** [comment]
@danielboniface the URL for the embed will be (when it's done) http://denverpostplus.com/app/ncaa-bracket/2016/womens/ -- you can use that to start on the article that will contain the brackets.

**Comment by danielboniface** [comment]
@freejoe76 Oooops, there's no first four in Women's. My bad. Can you delete that from the bracket?

**Comment by freejoe76** [comment]
Sure!

**Comment by freejoe76** [comment]
Okay this is done. http://denverpostplus.com/app/ncaa-bracket/2016/womens/
