### ISSUE TITLE
Second round isn't showing up at all in NCAA bracket

### ISSUE THREAD

**Issue by freejoe76** [denverpost/sports#27]
http://denverpostplus.com/app/ncaa-bracket/2016/

**Comment by freejoe76** [comment]
Fixed

**Comment by thejoenguyen** [comment]
Hey Joe, the top left side of the bracket looks like it's still down. Everything is working fine though.

**Comment by freejoe76** [comment]
Fixed. Had to delete the non-numeric text in the note column on the first spreadsheet, which is what fixed it. Seems you can have numbers or have words in the fields in the notes column, but once you go from one to the other it breaks. That's just great.
