### ISSUE TITLE
Rio Medals Count Widget

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#29]
Please add this Rio Olympics Medals Count widget to the extras server so that we can iframe it into articles.

<div id="ap_widget_container_f9f17347390ed2cd6867ade4b4902169"></div>
<script src="http://www.digitalservices.ap.org/widget-content/f9f17347390ed2cd6867ade4b4902169"></script>

**Comment by danielboniface** [comment]
<div id="ap_widget_container_f9f17347390ed2cd6867ade4b4902169"></div>
<script src="http://www.digitalservices.ap.org/widget-content/f9f17347390ed2cd6867ade4b4902169"></script>

**Comment by danielboniface** [comment]
`<div id="ap_widget_container_f9f17347390ed2cd6867ade4b4902169"></div>
<script src="http://www.digitalservices.ap.org/widget-content/f9f17347390ed2cd6867ade4b4902169"></script>`

**Comment by danielboniface** [comment]
@freejoe76 We'd like one that displays at 300 px wide, and one that fills the entire article.

**Comment by freejoe76** [comment]
Thanks @danielboniface. When do you want this ready by?

**Comment by danielboniface** [comment]
As soon as it's ready we'll start adding it to stories, @freejoe76.  It will display as a countdown clock until the games begin in 10 days. I have a few more widgets to request. I'll add those soon too.

**Comment by freejoe76** [comment]
Okay this is done, you can put it in articles with this markup. Adjust the width and height to suit.
```html
<aside class="related right">
<h2 class="widget-title"><a href="/weather">Weather</a></h2>
[dfm_iframe src="http://extras.denverpost.com/sports/widgets/olympic-medal-count.html" width="300px" height="750px"]
</aside>
