### ISSUE TITLE
Olympics Events Schedule widget

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#30]
Please add this code to an extras page so we can iframe in as a widget. 

`<div id="ap_widget_container_28bc0dd80c1a63ce43b59483fff6a042"></div>
<script src="http://www.digitalservices.ap.org/widget-content/28bc0dd80c1a63ce43b59483fff6a042"></script>`

**Comment by freejoe76** [comment]
Okay this is done, you can put it in articles with this markup. Adjust the width and height to suit.
```html
<aside class="related right">
<h2 class="widget-title"><a href="/weather">Weather</a></h2>
[dfm_iframe src="http://extras.denverpost.com/sports/widgets/olympic-events.html" width="300px" height="750px"]
</aside>```
