### ISSUE TITLE
Olympics Latest News Widget

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#31]
Please add this to an extras page so we can iframe into stories.

`<div id="ap_widget_container_2a44e627ede6e0c00c27e9c454f8bfe6"></div>
<script src="http://www.digitalservices.ap.org/widget-content/2a44e627ede6e0c00c27e9c454f8bfe6"></script>`

**Comment by freejoe76** [comment]
Okay this is done, you can put it in articles with this markup. Adjust the width and height to suit.
```html
<aside class="related right">
<h2 class="widget-title"><a href="/weather">Weather</a></h2>
[dfm_iframe src="http://extras.denverpost.com/sports/widgets/olympic-news.html" width="300px" height="750px"]
</aside>

**Comment by danielboniface** [comment]
Seeing a scrollbar at the story level when I added a couple of these widgets: [http://www.denverpost.com/2016/07/22/ioc-45-more-positive-cases-in-retests-of-2008-12-samples/](url)

@freejoe76

**Comment by danielboniface** [comment]
@freejoe76 oh wait... I just increased the iframe size and it fixed it.
