### ISSUE TITLE
Inside the Olympic Games widget

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#32]
Please add this to an extras page so we can iframe into stories.

`<div id="ap_widget_container_23c311266db56b228c755478cb8b590f"></div>
<script src="http://www.digitalservices.ap.org/widget-content/23c311266db56b228c755478cb8b590f"></script>`

**Comment by freejoe76** [comment]
Okay this is done, you can put it in articles with this markup. Adjust the width and height to suit.
```html
<aside class="related right">
<h2 class="widget-title"><a href="/weather">Weather</a></h2>
[dfm_iframe src="http://extras.denverpost.com/sports/widgets/olympic-insides.html" width="300px" height="750px"]
</aside>
