### ISSUE TITLE
NFL News widget

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#33]
Please add this to extras so we can iframe into stories.

`<div id="ap_widget_container_381c48efda23cbe188385de86ea0db74"></div>
<script src="http://www.digitalservices.ap.org/widget-content/381c48efda23cbe188385de86ea0db74"></script>`

**Comment by freejoe76** [comment]
Okay this is done, you can put it in articles with this markup. Adjust the width and height to suit.
```html
<aside class="related right">
<h2 class="widget-title"><a href="/weather">Weather</a></h2>
[dfm_iframe src="http://extras.denverpost.com/sports/widgets/nfl-news.html" width="300px" height="750px"]
</aside>
