### ISSUE TITLE
Embed video players on extras pages

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#36]
Please create an extras page for each of the following SendToNews video players, then send me the link so that I can set them up as widgets on each section front.

Sports Home:
<div class='s2nPlayer-0xAoFqwu' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=0xAoFqwu&cid=5163&SIZE=500' data-type='s2nScript'></script>

Rockies
<div class='s2nPlayer-SKKei7oz' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=SKKei7oz&cid=5163&SIZE=500' data-type='s2nScript'></script>

Broncos
<div class='s2nPlayer-7mI6Lnly' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=7mI6Lnly&cid=5163&SIZE=500' data-type='s2nScript'></script>

Nuggets
<div class='s2nPlayer-bRTYxcR1' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=bRTYxcR1&cid=5163&SIZE=500' data-type='s2nScript'></script>

Avalanche
<div class='s2nPlayer-W0U9H4zB' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=W0U9H4zB&cid=5163&SIZE=500' data-type='s2nScript'></script>

Golf
<div class='s2nPlayer-q0ePGjdP' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=q0ePGjdP&cid=5163&SIZE=500' data-type='s2nScript'></script>

Motorsports
<div class='s2nPlayer-r4z1WDg8' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=r4z1WDg8&cid=5163&SIZE=500' data-type='s2nScript'></script>

**Comment by schneidan** [comment]
Done. Here are the URLS:

```http://extras.denverpost.com/sports-video/avalanche.html
http://extras.denverpost.com/sports-video/broncos.html
http://extras.denverpost.com/sports-video/golf.html
http://extras.denverpost.com/sports-video/motorsports.html
http://extras.denverpost.com/sports-video/nuggets.html
http://extras.denverpost.com/sports-video/rockies.html
http://extras.denverpost.com/sports-video/sports.html```

**Comment by danielboniface** [comment]
@schneidan We want to update the code in the extras iframes to get the video to pop out and float to increase viewability and revenue. This is an example of what the Rockies one should look like. Can you add the changes to all iframes?

`<div class='s2nPlayer k-j4pmCl3u' data-type='float'></div><script type='text/javascript' src='http://embed.sendtonews.com/player3/embedcode.js?fk=j4pmCl3u&cid=5163&offsetx=0&offsety=0&floatwidth=400&floatposition=bottom-right' data-type='s2nScript'></script>`

**Comment by schneidan** [comment]
This won't work on DP.com; the popout would only be able to attach within the iframe itself, because it won't have access to the parent window.
