### ISSUE TITLE
Create a new extras page for this College Sports video player

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#39]
Hello, please create an extras page for this that we can iframe onto the College Sports section front, similar to how we've done with Sports, Broncos, Rockies, etc...

`<div class='s2nPlayer-R8GcBwEU' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=R8GcBwEU&cid=5163&SIZE=400' data-type='s2nScript'></script>`

**Comment by schneidan** [comment]
Can you paste an example of the ones you already have in here?

**Comment by danielboniface** [comment]
Here's the one we have on the Sports page:

http://extras.denverpost.com/sports-video/sports.html

**Comment by schneidan** [comment]
Give this a try, seems to be working:

http://extras.denverpost.com/sports-video/colleges.html

**Comment by danielboniface** [comment]
you da man, thanks!
