### ISSUE TITLE
Can you swap the embed code on this page?

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#40]
http://extras.denverpost.com/sports-video/sports.html

Replace the code with this, please:
`<div class='s2nPlayer-LczGSJbM' data-type='barker'></div><script type='text/javascript' src='http://embed.sendtonews.com/player2/embedcode.php?fk=LczGSJbM&cid=5163&SIZE=500' data-type='s2nScript'></script>`

Thanks!

**Comment by schneidan** [comment]
Sure. Done.

**Comment by danielboniface** [comment]
Thanks!
