### ISSUE TITLE
Please create an extras page we can iframe for Olympic Medals Count

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#41]
Hello,

Can you create an extras page we can iframe into an article page for the Winter Olympics medals count? It would need to be on an https page.

```
<div id="ap_widget_container_01802b9727014292b7c023f312009aec"></div>
<script src="https://digitalservices.ap.org/widget-content/01802b9727014292b7c023f312009aec"></script>
```

**Comment by schneidan** [comment]
I need to know where it's going to go on the page so I know what shape to make it...

**Comment by danielboniface** [comment]
Can you make one for an article page that we can gear toward search traffic, and one for the right rail that we can turn into a widget?

**Comment by schneidan** [comment]
Emailed response.
