### ISSUE TITLE
Please create an extras page we can iframe for the Latest News from the Winter Games

### ISSUE THREAD

**Issue by danielboniface** [denverpost/sports#43]
Hello,

Please create an extras page we can iframe into either an article or a right rail widget with the latest news from the Winter Games. It would need to be an https page.

```
<div id="ap_widget_container_b7cf84a581d88cca45de40c0719447cf"></div>
<script src="https://digitalservices.ap.org/widget-content/b7cf84a581d88cca45de40c0719447cf"></script>
```

**Comment by schneidan** [comment]
Would you want this to be an aside that floats right/left in an article? Or o all the way across?

**Comment by danielboniface** [comment]
I was thinking all the way across on this one, and we'll embed it at the bottom of each Olympics story.

**Comment by schneidan** [comment]
Emailed response.
