### ISSUE TITLE
Social Share Bar

### ISSUE THREAD

**Issue by danielpetty** [denverpost/sports#7]
Create a social share bar that includes an aggregate number of shares between all calculated social networks: Facebook, Twitter, Google Plus, LinkedIn. Found examples here: 

http://mashable.com/2014/11/12/us-china-climate-goals/
http://www.outsideonline.com/snow/snow-report/British-Columbia-Backcountry-Ski-Lodges.html

**Comment by freejoe76** [comment]
Moved to https://github.com/denverpost/social/issues/2
